### PR TITLE
Add test cases for Review

### PR DESCRIPTION
**Pull request by rockman007372**

### CODE REVIEW

**Comment by ruiyigan** [comment]
I don't think we should have a constructor just for testing in our actual code. Better to separate testing and production code. Can add it as a stub or something to the test class instead?

**Comment by rockman007372** [comment]
> I don't think we should have a constructor just for testing in our actual code. Better to separate testing and production code. Can add it as a stub or something to the test class instead?

Yep you are right! Therefore following this [instruction](https://stackoverflow.com/questions/9456118/test-a-class-that-uses-random-values), I inject a random with a predetermine seed into our Review instead! Do you think this works?

**Comment by ruiyigan** [comment]
Yup i think this looks good!

**Comment by rockman007372** [comment]
> Yup i think this looks good! Although I don't get why code cov dropp even tho got more test cases

Yep thats why i dont wanna merge :/

I think its because I add the equal method to the class Review. Its mostly for testing purposes... Should I remove it?

**Pull request closed without merging**
