### PR TITLE
Theme update

### PR DESCRIPTION
**Pull request by junianob**
image

Theme has been further updated with changes to the commandbox, display and padding on both deck and card list. Border on commandbox still needs to be removed! ( I wasn't able to locate the code responsible for it)

### CODE REVIEW

**Review by unfazing — CHANGES_REQUESTED** [review]
- What are the 2 black bars in the text input box? 
- Light grey background colours (both for the components and application background) are too dark (see UI mockup for values)
- Padding and radius of the components are not accurate to UI mockup.
- Name of application at topbar to be amended to PowerCards

**Review by ruiyigan — APPROVED** [review]
LGTM!

**Comment by junianob** [comment]
1. has been fixed!
2. has been fixed!
3. partially fixed!
4. Working on it

**Comment by junianob** [comment]
4. is done!

**Review by ruiyigan — APPROVED** [review]

**Pull request merged**
