### PR TITLE
Change scroll bar and fix graphical bug

### PR DESCRIPTION
**Pull request by junianob**
image

Scroll bar is now more theme appropriate. Also fixed an issue with the background radius when the cells overflow out of the visible box.

### CODE REVIEW

**Comment by junianob** [comment]
image

Text is now left aligned to fix text truncation issues. Will be working on a more elegant fix.
All inner containers are now padded with a dropshadow to separate them from the background.
Tag color has been changed. I was thinking of color coding green -> easy, orange -> medium, red-> hard
but it looks like tags can be any string. Let me know if there's any recommended color scheme.

**Review by rockman007372 — APPROVED** [review]
UI looking clean so far!

**Comment by rockman007372** [comment]
> image

It seems the container of the deck list is not fully rounded? The 2 bottom corners are square but the 2 top corners are rounded.

**Comment by rockman007372** [comment]
Will there be a way to separate Question from Answer? maybe different colour / font / headings... Right now they are a bit indistinguishable

**Comment by junianob** [comment]
image
Tags are now color coded! 
[easy] tag will be green, 
[medium] tag will be orange 
and [hard] tag will be red. 
Other tags will be gray.

**Pull request merged**
