### PR TITLE
Rework Navguide for Review

### PR DESCRIPTION
**Pull request by junianob**
image

Navguide in the review section is now a single image for better clarity. 

Current image shown [navguide.png] is just a placeholder at the moment. Detailed explanation of what each key does needs to be reflected in the image.

There's some width issues that needs to be fixed, will be working on that.

### CODE REVIEW

**Comment by rockman007372** [comment]
How do you plan to provide explanation for each key? On the diagram itself or just text?

**Comment by junianob** [comment]
image

Reworked navguide to be more intuitive. PSD is also attached if a design change/improvement is needed.


Review is currently a bit buggy at the moment. Right now updateItem() in ReviewStatsPanel.java is updating multiple instances of the same element in the ReviewStatPanel, leading to unintended results.
image

From debugging, issue does not seem to be from LogicManager.java, ModelManager.java or Review.java as the getReviewStatsList method is only called once.

Issue could be in MainWindow.java or somewhere else in UI handling.
@unfazing @ruiyigan Some advice needed please.

**Comment by rockman007372** [comment]
> image
> 
> Reworked navguide to be more intuitive. PSD is also attached if a design change/improvement is needed.
> 
> Review is currently a bit buggy at the moment. Right now updateItem() in ReviewStatsPanel.java is updating multiple instances of the same element in the ReviewStatPanel, leading to unintended results. image
> 
> From debugging, issue does not seem to be from LogicManager.java, ModelManager.java or Review.java as the getReviewStatsList method is only called once.
> 
> Issue could be in MainWindow.java or somewhere else in UI handling. @unfazing @ruiyigan Some advice needed please.

`updateItem()` in ReviewStatPanel will be called everytime the ObservableList `reviewStatList` is modified. Current when we call the method `updateReviewStatsList` in Review, the Observale List is modified twice (clear, then add). Is this potentially the source of your issue?

image

**Comment by junianob** [comment]
> > Review is currently a bit buggy at the moment. Right now updateItem() in ReviewStatsPanel.java is updating multiple instances of the same element in the ReviewStatPanel, leading to unintended results. image
> > From debugging, issue does not seem to be from LogicManager.java, ModelManager.java or Review.java as the getReviewStatsList method is only called once.
> > Issue could be in MainWindow.java or somewhere else in UI handling. @unfazing @ruiyigan Some advice needed please.
> 
> `updateItem()` in ReviewStatPanel will be called everytime the ObservableList `reviewStatsList` is modified. Current when we call the method `updateReviewStatsList` in Review, the Observable List is modified twice (clear, then add). Is this potentially the source of your issue?
> 
> image

I doubt this is the case... from my testing, modifying the ObservableList just once or multiple times results in the same issue.

**Comment by unfazing** [comment]
could you make this a feature branch on our remote repo so we can pull and debug. thanks!

**Comment by rockman007372** [comment]
Settled!

**Pull request closed without merging**
