### PR TITLE
Enable Decks to be saved in JSON format

### LINKED ISSUE #105: Feature - enable storage of decks without cards
Currently the empty decks will not be stored as the storage initialises the unique decks by parsing through the existing cards in the stored json. Empty decks created by the user will not have a card with that deck and thus will be lost after the session ends.

### PR DESCRIPTION
**Pull request by rockman007372**
This PR allows decks to be saved in JSON format. Other changes include:
- Allows decks with no card to be saved.
- Throws exception if a JSON card exists without an existing deck.
- Modify equal method in MasterDeck to compare deck list too.
- 

Note:
- Delete your addressbook.json file before loading the app, the old data should be in incorrect format (no JSON deck).
- Some test methods were adding cards without creating a deck, through the MasterDeck::addCard method. Should we modify addCard so that if we add a card, we also add a deck if the deck is not found?

Closes #105

### CODE REVIEW

**Comment by rockman007372** [comment]
Wait are the test data ignored in .gitignore? I cannot push it to the PR

**Comment by rockman007372** [comment]
Code Coverage decreased due to added functionality of storing deck in JSON format.

**Comment by ruiyigan** [comment]
To check, the Deck class in each Card is not referenced to the Decks in the list of Decks? Ie: we are not creating the Deck objects first and then passing the Deck object to create the Card.

**Comment by rockman007372** [comment]
> To check, the Deck class in each Card is not referenced to the Decks in the list of Decks? Ie: we are not creating the Deck objects first and then passing the Deck object to create the Card.

Not in the current implementation. Righ now we are using the overwritten equals method to check to if the Deck in the Card is the semantically equal to the Deck in the Deck List.

**Comment by unfazing** [comment]
Are there any checks to ensure that the saved decks contain all the unique decks that the saved cards belong to?

e.g. i have 100 cards saved from 10 different decks. i shld guarantee that the deck json has at least those 10 different decks when i am saving the json and when i am loading the json for it to be valid.

**Comment by rockman007372** [comment]
> Are there any checks to ensure that the saved decks contain all the unique decks that the saved cards belong to?
> 
> e.g. i have 100 cards saved from 10 different decks. i shld guarantee that the deck json has at least those 10 different decks when i am saving the json and when i am loading the json for it to be valid.
> 
> We shld support users directly editing on the saved files (as is supported by ab3), so we need to check the validity of the save before loading.

Is this to prevent cards that exist without a deck? Currently this check is missing. I can add this check and update ASAP.

To clarify, you propose this check be made when the app loads the save file?

**Comment by rockman007372** [comment]
CodeCo bugged. New PR at #114

**Pull request closed without merging**
